/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container-highest": "#e0e3e5",
        "secondary": "#006876",
        "surface-bright": "#f7f9fb",
        "on-primary-fixed": "#00201c",
        "on-tertiary-fixed-variant": "#763219",
        "on-secondary-fixed-variant": "#004e59",
        "primary-container": "#008376",
        "primary": "#00685d",
        "secondary-fixed-dim": "#55d7ed",
        "on-surface": "#191c1e",
        "error": "#ba1a1a",
        "tertiary-fixed": "#ffdbcf",
        "inverse-on-surface": "#eff1f3",
        "surface-container": "#eceef0",
        "on-primary": "#ffffff",
        "on-tertiary-container": "#fffbff",
        "outline": "#6d7a77",
        "surface": "#f7f9fb",
        "surface-container-high": "#e6e8ea",
        "on-background": "#191c1e",
        "surface-container-lowest": "#ffffff",
        "inverse-primary": "#70d8c8",
        "surface-variant": "#e0e3e5",
        "on-primary-fixed-variant": "#005048",
        "on-surface-variant": "#3d4946",
        "inverse-surface": "#2d3133",
        "on-error-container": "#93000a",
        "outline-variant": "#bcc9c5",
        "on-tertiary": "#ffffff",
        "on-secondary-fixed": "#001f24",
        "primary-fixed-dim": "#70d8c8",
        "tertiary-fixed-dim": "#ffb59c",
        "on-tertiary-fixed": "#390c00",
        "surface-container-low": "#f2f4f6",
        "tertiary-container": "#b05e41",
        "secondary-fixed": "#9eefff",
        "background": "#f7f9fb",
        "surface-dim": "#d8dadc",
        "surface-tint": "#006b5f",
        "on-secondary-container": "#006774",
        "primary-fixed": "#8df5e4",
        "on-error": "#ffffff",
        "secondary-container": "#69e8fe",
        "on-primary-container": "#f4fffb",
        "on-secondary": "#ffffff",
        "tertiary": "#91462c",
        "error-container": "#ffdad6"
      },
      fontFamily: {
        headline: ["Manrope", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"]
      }
    },
  },
  plugins: [],
}
